### ISSUE TITLE
Auswahl an Antwortmöglichkeiten

### ISSUE THREAD

**Issue by vilnius-leopold** [vilnius-leopold/big-band-dudel#4]
- Einen Bereich, in dem (evtl. dann über einen log-in, muss aber auch nicht) ein paar Einstellungen bearbeitet werden können. z.B. Auswahl an Antwortmöglichkeiten; Farben etc. (ähnlich dieser Seite: https://dudel.mafiasi.de/brazz/values/)

**Comment by vilnius-leopold** [comment]
Dieses feature ist vielleicht unnötig. Ich denk mir es ist einfacher wenn ihr mir einfach sagt was ihr braucht wenn ihr etwas ändern wollt. Ich denk das Verhältnis zwischen wie oft ihr die Funktion verwenden werdet und der Arbeitsaufwand der dahinter steckt dieses Feature zu implementieren rechtfertigt es nicht. Oder werden sich die Antwortmöglichkeiten sehr häufig ändern?

**Comment by Woruman** [comment]
Ok. Ich dachte halt, dann ist das Dudel vielseitiger nutzbar. Für die Brazzband aber sicherlich nicht nötig.

**Comment by vilnius-leopold** [comment]
@Woruman ich versteh. Jedoch halte ich es immer fuer besser unoetige features einzudampfen. Projekte haben die Tendenz ins unermaessliche zu wachsen, woran sie am Ende scheitern. Das moechte ich verhindern. Vor Allem in der Anfangsphase.

Spaeter koennen wir immer noch Features hinzufuegen. Aber fuer den Anfang sollten wir uns auf das Wesentliche konzentrieren und wenn das gut funktioniert, dann schauen wir weiter.

A propos... bist du torben oder steffen :D

**Comment by Woruman** [comment]
Am 21.06.2016 um 00:15 schrieb vilnius-leopold:

> @Woruman ich versteh. Jedoch halte ich es immer fuer besser unoetige features einzudampfen. Projekte haben die Tendenz ins unermaessliche zu wachsen, woran sie am Ende scheitern. Das moechte ich verhindern. Vor Allem in der Anfangsphase.

Ja, ist ok.

> Spaeter koennen wir immer noch Features hinzufuegen. Aber fuer den Anfang sollten wir uns auf das Wesentliche konzentrieren und wenn das gut funktioniert, dann schauen wir weiter.
> 
> A propos... bist du torben oder steffen :D

Steffin

**Comment by Woruman** [comment]
wouldn't it possible to use the code from the mafiasi.dudel?

Yeah, you're right with keeping it simple. But I think, the mafiasidudel
seems to have much of the functions we would like to have. so why not
taking and modificating it?

thanks,

Steffin

Am 21.06.2016 um 22:41 schrieb vilnius-leopold:

**Comment by vilnius-leopold** [comment]
@Woruman in theroy YES. In practice NO. :D It's this sad reality of programming. Nobody likes to touch over peoples code unless it's totally necessary.

The reality is, often it is much easier to write your own application with the language and tools you are used to than to try to understand the code someone else wrote.

Anyone who has worked in the programming field will tell you there is nothing closer to torture than working with other peoples code :D

 I know it feels like a waste of time and effort. But that's just how it is.

**Comment by Woruman** [comment]
Ok, I understand. Thank you for your explanations. I really have no idea
of your working as programmer.

But anyway, I think, we can use the mafiasi dudel as model for good and
bad funktions.

I don't know if torben has forwarded the Mail I wrote about functions
I'd like to have. In this mail I nearly always referred to the
mafiasi.dudel to show, what I like, what I miss and so on....
Perhabs my mail was not understable/too long/too confusing...

Perhabs I'll find time in some days to put the issues mentioned in the
mail on github. I can't promise, cause I'm really stressed with
university stuff...

So my suggestion is to orientate in programming on the mentioned
functions of dudel mafiasi.

;)

Am 23.06.2016 um 14:46 schrieb vilnius-leopold:
